#pragma once

#ifndef COEFICIENTES_REFRACCION_H
#define COEFICIENTES_REFRACCION_H

const float COEFICIENTE_REFRACCION_VACIO = 1.00000f;
const float COEFICIENTE_REFRACCION_AIRE = 1.00029f;
const float COEFICIENTE_REFRACCION_ACETONA = 1.36f;
const float COEFICIENTE_REFRACCION_ALCOHOL = 1.329f;
const float COEFICIENTE_REFRACCION_SELENIO_AMORFO = 2.92f;
const float COEFICIENTE_REFRACCION_CALSPAR_1 = 1.66f;
const float COEFICIENTE_REFRACCION_CALSPAR_2 = 1.486f;
const float COEFICIENTE_REFRACCION_DISULFURO_DE_CARBONO = 1.63f;
const float COEFICIENTE_REFRACCION_OXIDO_DE_CROMO = 2.705f;
const float COEFICIENTE_REFRACCION_OXIDO_DE_COBRE = 2.705f;
const float COEFICIENTE_REFRACCION_VIDRIO_DE_CORONA = 1.52f;
const float COEFICIENTE_REFRACCION_CRISTAL = 2.00f;
const float COEFICIENTE_REFRACCION_DIAMANTE = 2.417f;
const float COEFICIENTE_REFRACCION_ESMERALDA = 1.57f;
const float COEFICIENTE_REFRACCION_ALCOHOL_ETILICO = 1.36f;
const float COEFICIENTE_REFRACCION_FLUORITA = 1.434f;
const float COEFICIENTE_REFRACCION_CUARZO_FUNDIDO = 1.46f;
const float COEFICIENTE_REFRACCION_VIDRIO_FLINT_PESADO = 1.89f;
const float COEFICIENTE_REFRACCION_VIDRIO_FLINT = 1.65f;
const float COEFICIENTE_REFRACCION_VIDRIO = 1.5f;
const float COEFICIENTE_REFRACCION_HIELO = 1.309f;
const float COEFICIENTE_REFRACCION_CRISTAL_DE_YODO = 3.34f;
const float COEFICIENTE_REFRACCION_LAPISLAZULI = 1.61f;
const float COEFICIENTE_REFRACCION_VIDRIO_FLINT_LIGERO = 1.575f;
const float COEFICIENTE_REFRACCION_DIOXIDO_DE_CARBONO_LIQUIDO = 1.20f;
const float COEFICIENTE_REFRACCION_POLIESTIRENO = 1.55f;
const float COEFICIENTE_REFRACCION_CUARZO_1 = 1.644f;
const float COEFICIENTE_REFRACCION_CUARZO_2 = 1.553f;
const float COEFICIENTE_REFRACCION_RUBI = 1.77f;
const float COEFICIENTE_REFRACCION_ZAFIRO = 1.77f;
const float COEFICIENTE_REFRACCION_CLORURO_DE_SODIO_SAL_1 = 1.544f;
const float COEFICIENTE_REFRACCION_CLORURO_DE_SODIO_SAL_2 = 1.644f;
const float COEFICIENTE_REFRACCION_SOLUCION_DE_AZUCAR_30_70 = 1.38f;
const float COEFICIENTE_REFRACCION_SOLUCION_DE_AZUCAR_80_20 = 1.49f;
const float COEFICIENTE_REFRACCION_TOPACIO = 1.61f;
const float COEFICIENTE_REFRACCION_AGUA_20C = 1.333f;
const float COEFICIENTE_REFRACCION_VIDRIO_DE_CORONA_DE_ZINC = 1.517f;

#endif
